In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import pandas_profiling
import  numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('Advertising.csv')

In [4]:
df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [5]:
df = df.drop(columns=['Unnamed: 0'],axis = 1)

In [6]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [7]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
df.tail()

TV  radio  newspaper  sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [9]:
df.isnull().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [10]:
df.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [11]:
df.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [12]:
pf = df.profile_report()

Summarize dataset:   0%|          | 0/17 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [14]:
 df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [15]:
X = df[['TV']]

In [16]:
X

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [17]:
y = df.sales

In [18]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
linear = LinearRegression()

In [21]:
linear.fit(X,y)

LinearRegression()

In [22]:
linear.coef_

array([0.04753664])

In [23]:
linear.intercept_

7.032593549127693

In [24]:
file = 'linear_reg.sav'
pickle.dump(linear,open(file,'wb'))

In [25]:
linear.predict([[45]])

array([9.17174237])

In [26]:
(0.047*45)+7.01

9.125

In [27]:
l = [45,5,6,7,89,34,67,23,45,478,4562]

In [28]:
for i in l:
    linear.predict([[i]])
    print(linear.predict([[i]]))

[9.17174237]
[7.27027675]
[7.31781339]
[7.36535003]
[11.26335455]
[8.64883932]
[10.21754846]
[8.12593628]
[9.17174237]
[29.75510768]
[223.8947472]


In [29]:
linear.score(X,y)

0.611875050850071

## Mutilinear Regression

In [30]:
 df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

High Bias and Low Bias

In [31]:
df.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [32]:
X = df[['TV', 'radio', 'newspaper']]

In [33]:
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [34]:
y = df.sales

In [35]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [36]:
lm = LinearRegression()

In [37]:
lm.fit(X,y)

LinearRegression()

In [38]:
lm.intercept_

2.9388893694594085

In [39]:
lm.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

y = 0.04*TV + 0.18*Radio - 0.001*Newspaper + 2.93

In [40]:
lm.score(X,y)

0.8972106381789522

In [41]:
X = df[['TV','radio']]
y  = df.sales

In [42]:
lm = LinearRegression()

In [43]:
lm.fit(X,y)

LinearRegression()

In [44]:
lm.score(X,y)

0.8971942610828956

 ## Statistical Analysis for Feature Selection

In [45]:
import statsmodels.formula.api as smf

In [46]:
lm = smf.ols(formula = 'sales ~ TV', data = df).fit()

In [47]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Thu, 02 Sep 2021   Prob (F-statistic):           1.47e-42
Time:                        20:25:18   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.000       6.130       7.935
TV             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================
Omnibus:                        0.531   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.767   Jarque-Bera (JB):                0.669
Skew:                          -0.089   Prob(JB):                        0.716
Kurtosis:                       2.779   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [48]:
lm1 = smf.ols(formula = 'sales ~ TV + radio', data = df).fit()

In [49]:
lm1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     859.6
Date:                Thu, 02 Sep 2021   Prob (F-statistic):           4.83e-98
Time:                        20:25:18   Log-Likelihood:                -386.20
No. Observations:                 200   AIC:                             778.4
Df Residuals:                     197   BIC:                             788.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9211      0.294      9.919      0.000       2.340       3.502
TV             0.0458      0.001     32.909      0.000       0.043       0.048
radio          0.1880      0.008     23.382      0.000       0.172       0.204
==============================================================================
Omnibus:                       60.022   Durbin-Watson:                   2.081
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              148.679
Skew:                          -1.323   Prob(JB):                     5.19e-33
Kurtosis:                       6.292   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [50]:
lm2 = smf.ols(formula = 'sales ~ TV + radio + newspaper', data = df).fit()
lm2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Thu, 02 Sep 2021   Prob (F-statistic):           1.58e-96
Time:                        20:25:18   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
radio          0.1885      0.009     21.893      0.000       0.172       0.206
newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

## Admission Prediction Model

In [187]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,LassoCV,RidgeCV, ElasticNet,ElasticNetCV,LinearRegression,Lasso
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

## 1. Data preprocessing

In [52]:
df = pd.read_csv('Admission_Prediction.csv')

In [53]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [54]:
df = df.drop(columns=['Serial No.'],axis = 1)

In [55]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0        337.0        118.0                4.0  4.5  4.5  9.65         1   
1        324.0        107.0                4.0  4.0  4.5  8.87         1   
2          NaN        104.0                3.0  3.0  3.5  8.00         1   
3        322.0        110.0                3.0  3.5  2.5  8.67         1   
4        314.0        103.0                2.0  2.0  3.0  8.21         0   
..         ...          ...                ...  ...  ...   ...       ...   
495      332.0        108.0                5.0  4.5  4.0  9.02         1   
496      337.0        117.0                5.0  5.0  5.0  9.87         1   
497      330.0        120.0                5.0  4.5  5.0  9.56         1   
498      312.0        103.0                4.0  4.0  5.0  8.43         0   
499      327.0        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

## 2. EDA

In [56]:
pf = df.profile_report()

In [57]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/21 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

## 3. Handeling Missing Value

In [58]:
df.isnull().sum()

GRE Score            15
TOEFL Score          10
University Rating    15
SOP                   0
LOR                   0
CGPA                  0
Research              0
Chance of Admit       0
dtype: int64

In [59]:
df.describe()

GRE Score  TOEFL Score  University Rating         SOP        LOR  \
count  485.000000   490.000000         485.000000  500.000000  500.00000   
mean   316.558763   107.187755           3.121649    3.374000    3.48400   
std     11.274704     6.112899           1.146160    0.991004    0.92545   
min    290.000000    92.000000           1.000000    1.000000    1.00000   
25%    308.000000   103.000000           2.000000    2.500000    3.00000   
50%    317.000000   107.000000           3.000000    3.500000    3.50000   
75%    325.000000   112.000000           4.000000    4.000000    4.00000   
max    340.000000   120.000000           5.000000    5.000000    5.00000   

             CGPA    Research  Chance of Admit  
count  500.000000  500.000000        500.00000  
mean     8.576440    0.560000          0.72174  
std      0.604813    0.496884          0.14114  
min      6.800000    0.000000          0.34000  
25%      8.127500    0.000000          0.63000  
50%      8.560000    1.000000          0.72000  
75%      9.040000    1.000000          0.82000  
max      9.920000    1.000000          0.97000

In [60]:
df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0      337.0        118.0                4.0  4.5  4.5  9.65         1   
1      324.0        107.0                4.0  4.0  4.5  8.87         1   
2        NaN        104.0                3.0  3.0  3.5  8.00         1   
3      322.0        110.0                3.0  3.5  2.5  8.67         1   
4      314.0        103.0                2.0  2.0  3.0  8.21         0   

   Chance of Admit  
0             0.92  
1             0.76  
2             0.72  
3             0.80  
4             0.65

In [61]:
df['GRE Score'] = df['GRE Score'].fillna(df['GRE Score'].mean())

In [62]:
df.isnull().sum()

GRE Score             0
TOEFL Score          10
University Rating    15
SOP                   0
LOR                   0
CGPA                  0
Research              0
Chance of Admit       0
dtype: int64

In [63]:
df['TOEFL Score'] = df['TOEFL Score'].fillna(df['TOEFL Score'].mean())

In [64]:
df['University Rating'] = df['University Rating'].fillna(df['University Rating'].mean())

In [65]:
df.isnull().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [66]:
pf1 = df.profile_report()
pf1.to_widgets()

Summarize dataset:   0%|          | 0/21 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

## 4. Column Treatment

In [67]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA',
       'Research', 'Chance of Admit'],
      dtype='object')

In [68]:
df.columns 

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA',
       'Research', 'Chance of Admit'],
      dtype='object')

In [69]:
df.rename(columns={'GRE Score':'GRE_Score',
                  'TOEFL Score':'TOEFL_Score',
                  'University Rating':'University_Rating',
                  'SOP':'SOP','LOR':'LOR','CGPA':'CGPA',
                  'Research':'Research','Chance of Admit':'Chance_of_Admit'},inplace=True)

In [70]:
df.columns

Index(['GRE_Score', 'TOEFL_Score', 'University_Rating', 'SOP', 'LOR', 'CGPA',
       'Research', 'Chance_of_Admit'],
      dtype='object')

## 5. Statistical Analysis

In [71]:
df

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance_of_Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [72]:
lm = smf.ols(formula = 'Chance_of_Admit ~ GRE_Score',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:        Chance_of_Admit   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     899.7
Date:                Thu, 02 Sep 2021   Prob (F-statistic):          1.13e-113
Time:                        20:25:59   Log-Likelihood:                 528.02
No. Observations:                 500   AIC:                            -1052.
Df Residuals:                     498   BIC:                            -1044.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -2.5065      0.108    -23.274      0.000      -2.718      -2.295
GRE_Score      0.0102      0.000     29.994      0.000       0.010       0.011
==============================================================================
Omnibus:                       49.583   Durbin-Watson:                   0.955
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               71.129
Skew:                          -0.706   Prob(JB):                     3.59e-16
Kurtosis:                       4.191   Cond. No.                     9.04e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.04e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [73]:
lm = smf.ols(formula = 'Chance_of_Admit ~ GRE_Score +TOEFL_Score + University_Rating + SOP + LOR + CGPA + Research',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:        Chance_of_Admit   R-squared:                       0.821
Model:                            OLS   Adj. R-squared:                  0.818
Method:                 Least Squares   F-statistic:                     321.7
Date:                Thu, 02 Sep 2021   Prob (F-statistic):          4.36e-179
Time:                        20:25:59   Log-Likelihood:                 699.68
No. Observations:                 500   AIC:                            -1383.
Df Residuals:                     492   BIC:                            -1350.
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            -1.2665      0.104    -12.153      0.000      -1.471      -1.062
GRE_Score             0.0018      0.000      3.576      0.000       0.001       0.003
TOEFL_Score           0.0027      0.001      3.148      0.002       0.001       0.004
University_Rating     0.0051      0.004      1.359      0.175      -0.002       0.013
SOP                   0.0022      0.005      0.486      0.627      -0.007       0.011
LOR                   0.0166      0.004      4.000      0.000       0.008       0.025
CGPA                  0.1213      0.010     12.621      0.000       0.102       0.140
Research              0.0258      0.007      3.936      0.000       0.013       0.039
==============================================================================
Omnibus:                      109.964   Durbin-Watson:                   0.808
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              246.613
Skew:                          -1.147   Prob(JB):                     2.81e-54
Kurtosis:                       5.564   Cond. No.                     1.30e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.3e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [74]:
lm = smf.ols(formula = 'Chance_of_Admit ~ GRE_Score +TOEFL_Score + University_Rating  + LOR + CGPA + Research',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:        Chance_of_Admit   R-squared:                       0.821
Model:                            OLS   Adj. R-squared:                  0.818
Method:                 Least Squares   F-statistic:                     375.8
Date:                Thu, 02 Sep 2021   Prob (F-statistic):          2.43e-180
Time:                        20:25:59   Log-Likelihood:                 699.56
No. Observations:                 500   AIC:                            -1385.
Df Residuals:                     493   BIC:                            -1356.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            -1.2730      0.103    -12.324      0.000      -1.476      -1.070
GRE_Score             0.0018      0.000      3.563      0.000       0.001       0.003
TOEFL_Score           0.0028      0.001      3.220      0.001       0.001       0.004
University_Rating     0.0058      0.004      1.620      0.106      -0.001       0.013
LOR                   0.0172      0.004      4.356      0.000       0.009       0.025
CGPA                  0.1222      0.009     12.973      0.000       0.104       0.141
Research              0.0259      0.007      3.950      0.000       0.013       0.039
==============================================================================
Omnibus:                      108.480   Durbin-Watson:                   0.814
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              241.589
Skew:                          -1.135   Prob(JB):                     3.46e-53
Kurtosis:                       5.538   Cond. No.                     1.29e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.29e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## 6. Model Prepration 

In [75]:
df

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance_of_Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [76]:
X = df.drop(columns=['Chance_of_Admit'])

In [77]:
y = df.Chance_of_Admit

In [78]:
X

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [79]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance_of_Admit, Length: 500, dtype: float64

## 7. Data Transformation 

In [80]:
scaler = StandardScaler()

In [81]:
scaler.fit_transform(X)

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [82]:
x_scale = scaler.fit_transform(X)

In [83]:
df1 = pd.DataFrame(x_scale)

In [84]:
df1.profile_report()

Summarize dataset:   0%|          | 0/20 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [85]:
df1.describe()

0             1             2             3             4  \
count  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   4.350520e-15  9.419132e-16  5.608847e-16  2.926548e-16 -1.332268e-17   
std    1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -2.394225e+00 -2.512331e+00 -1.881441e+00 -2.397950e+00 -2.686789e+00   
25%   -6.814090e-01 -6.927310e-01 -9.946589e-01 -8.828175e-01 -5.235128e-01   
50%    5.124333e-15 -3.105811e-02 -1.078766e-01  1.272712e-01  1.730621e-02   
75%    6.708143e-01  7.960330e-01  7.789057e-01  6.323155e-01  5.581253e-01   
max    2.113186e+00  2.119379e+00  1.665688e+00  1.642404e+00  1.639763e+00   

                  5             6  
count  5.000000e+02  5.000000e+02  
mean   3.091971e-15 -2.202682e-16  
std    1.001002e+00  1.001002e+00  
min   -2.940115e+00 -1.128152e+00  
25%   -7.430227e-01 -1.128152e+00  
50%   -2.720919e-02  8.864053e-01  
75%    7.672196e-01  8.864053e-01  
max    2.223672e+00  8.864053e-01

## 8. Check Multicollinearity 

In [86]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [87]:
 x_scale.shape

(500, 7)

In [89]:
vif_df = pd.DataFrame()

In [90]:
vif_df['vif'] = [variance_inflation_factor(x_scale,i) for i in range( x_scale.shape[1])]

In [93]:
vif_df['features'] = X.columns

In [94]:
vif_df

vif           features
0  4.153268          GRE_Score
1  3.792866        TOEFL_Score
2  2.508768  University_Rating
3  2.775750                SOP
4  2.037308                LOR
5  4.651670               CGPA
6  1.459311           Research

## 9. Training and Testing Data

In [163]:
x_train,x_test,y_train,y_test = train_test_split(x_scale,y,test_size=0.25,random_state=35)

In [164]:
model = LinearRegression()

In [165]:
model.fit(x_train,y_train)

LinearRegression()

In [166]:
model.score(x_train,y_train)

0.8209061766026746

In [167]:
model.score(x_test,y_test)

0.8158797068035137

### Check Accuracy of Model

In [168]:
def adj_r2(x,y):
    r2 = model.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [169]:
adj_r2(x_train,y_train)

0.817490218118257

In [170]:
adj_r2(x_test,y_test)

0.8048639627661172

## 10. Model Dump

In [171]:
import pickle

In [172]:
pickle.dump(model,open('Admission_lr_model.pickle','wb'))

## 11. Prediction

In [173]:
df

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance_of_Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [174]:
model.predict([[337.00,118.0,4.0,4.5,4.5,9.65,1]])

array([9.13333947])

In [179]:
test1 = scaler.transform([[314,103,2,2,3,8.21,0]])
test1

array([[-0.23066792, -0.69273097, -0.99465886, -1.3878618 , -0.52351283,
        -0.6064802 , -1.12815215]])

In [176]:
test2 = scaler.transform([[324.000000,107.0,4.0,4.0,4.5,8.87,1]])
test2

array([[ 0.67081429, -0.03105811,  0.77890565,  0.63231549,  1.09894429,
         0.48585943,  0.88640526]])

In [177]:
model.predict([[1.84274116, 1.78854223, 0.77890565, 1.13735981, 1.09894429,
        1.77680627, 0.88640526]])

array([0.95272823])

In [178]:
model.predict([[ 0.67081429, -0.03105811,  0.77890565,  0.63231549,  1.09894429,
         0.48585943,  0.88640526]])

array([0.8058744])

In [180]:
model.predict([[-0.23066792, -0.69273097, -0.99465886, -1.3878618 , -0.52351283,
        -0.6064802 , -1.12815215]])

array([0.6226688])

## Model Equation

In [181]:
model.intercept_

0.7211671439089439

In [182]:
model.coef_

array([0.01674134, 0.01637765, 0.00402475, 0.00727881, 0.01630187,
       0.07262678, 0.01471891])

# 12. Regularization Technique

## 1. Lasso 

In [197]:
lassocv =LassoCV(cv = 100,max_iter=2000000,normalize=True)

In [198]:
lassocv.fit(x_train,y_train)

LassoCV(cv=100, max_iter=2000000, normalize=True)

In [199]:
lassocv.alpha_

6.417432411805146e-06

In [200]:
lasso = Lasso(alpha=lassocv.alpha_)

In [201]:
lasso.fit(x_train,y_train)

Lasso(alpha=6.417432411805146e-06)

### Accuracy Check

In [202]:
lasso.score(x_train,y_train)

0.8209061731397759

In [203]:
lasso.score(x_test,y_test)

0.8158866343679496

In [205]:
adj_r2(x_train,y_train)

0.817490218118257

In [206]:
adj_r2(x_test,y_test)

0.8048639627661172

## Ridge

In [209]:
alphas = np.random.uniform(low=0,high=10,size=(50,))

In [210]:
ridgecv = RidgeCV(alphas=alphas,cv =10,normalize=True)

In [211]:
ridgecv.fit(x_train,y_train)

RidgeCV(alphas=array([8.01970237, 4.55751998, 7.99271069, 0.7891711 , 3.88861732,
       4.37106149, 3.7952667 , 8.94441046, 7.52803817, 1.24775924,
       8.83468742, 1.45216909, 9.89643785, 1.8927076 , 0.53090026,
       7.84184575, 0.74148606, 5.45698159, 8.39975208, 0.77813256,
       5.88627259, 7.71459557, 4.31287223, 5.38834358, 4.63054292,
       5.13895521, 6.44181505, 0.01130803, 6.58052563, 8.33634626,
       1.21263724, 3.4678931 , 6.85218547, 9.03417786, 3.80224613,
       7.89438208, 6.50409434, 1.97214253, 0.41833661, 2.34665044,
       6.0613026 , 8.59200263, 5.8771447 , 3.37539079, 4.98244277,
       2.33461059, 9.14464147, 9.1679196 , 5.00620694, 0.11422177]),
        cv=10, normalize=True)

In [212]:
ridgecv.alpha_

0.011308030260614998

In [213]:
ridge_lr = Ridge(alpha = ridgecv.alpha_)
ridge_lr.fit(x_train,y_train)

Ridge(alpha=0.011308030260614998)

In [214]:
ridge_lr.score(x_train,y_train)

0.8209061758915801

In [215]:
ridge_lr.score(x_test,y_test)

0.8158795197119567

## Elastic Net

In [216]:
elastic_cv = ElasticNetCV(alphas=None,cv=10)
elastic_cv.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [217]:
elastic_cv.alpha_

0.0002488973608093338

In [218]:
elastic_cv.l1_ratio_

0.5

In [219]:
ElasticNet = ElasticNet(alpha=elastic_cv.alpha_,l1_ratio=elastic_cv.l1_ratio_)

In [220]:
ElasticNet.fit(x_train,y_train)

ElasticNet(alpha=0.0002488973608093338)

In [221]:
ElasticNet.score(x_train,y_train)

0.820904848293253

In [222]:
ElasticNet.score(x_test,y_test)

0.8159987521157861